'use strict';

import React, {
    Component,
    StyleSheet,
    Text,
    TextInput,
    TouchableHighlight,
    Image,
    View
} from 'react-native';

var PushNotification = require('react-native-push-notification');

PushNotification.configure({

    // (optional) Called when Token is generated (iOS and Android)
    onRegister: function(token) {
        console.log( 'TOKEN:', token );
    },

    // (required) Called when a remote or local notification is opened or received
    onNotification: function(notification) {
        console.log( 'NOTIFICATION:', notification );
    },

    // ANDROID ONLY: (optional) GCM Sender ID.
    senderID: "YOUR GCM SENDER ID",

    // IOS ONLY (optional): default: all - Permissions to register.
    permissions: {
        alert: true,
        badge: true,
        sound: true
    },

    // Should the initial notification be popped automatically
    // default: true
    popInitialNotification: true,

    /**
     * IOS ONLY: (optional) default: true
     * - Specified if permissions will requested or not,
     * - if not, you must call PushNotificationsHandler.requestPermissions() later
     */
    requestPermissions: true,
});

export default class CreateTask extends Component {

    componentWillMount() {
        this.setState({
            text: ''
        })
    }

	componentDidMount(){
		PushNotification.localNotification({
			/* Android Only Properties */
			id: 0, // (optional) default: Autogenerated Unique ID
			title: "My Notification Title", // (optional)
			ticker: "My Notification Ticker", // (optional)
			largeIcon: "ic_launcher", // (optional) default: "ic_launcher"
			smallIcon: "ic_notification", // (optional) default: "ic_notification" with fallback for "ic_launcher"

			/* iOS and Android properties */
			message: "My Notification Message" // (required)
		});

	}

    render() {
        const { actions, tasksActions } = this.props;
        return (
            <View style={styles.layout}>
                <Image source={require('../../resources/ui_boy.png')} style={styles.image}></Image>
                <Text style={styles.mediumSpan}>
                    Что еще ты придумал?
                </Text>
                <View style={styles.textInputWrapper}>
                    <TextInput
                        ref="text"
                        style={styles.textInput}
                        selectionColor="#fff"
                        onChangeText={(text) => this.setState({text})}
                        value={this.state.text} />
                </View>

                <TouchableHighlight style={styles.createTask}
                                    underlayColor="rgb(74, 134, 204)"
                                    onPress={() => { if(this.state.text) { tasksActions.addTask(this.state.text); actions.routes.home()();}}}>
                    <Text style={styles.createTaskText}>Cоздать задачу</Text>
                </TouchableHighlight>

                <TouchableHighlight style={styles.cancelTask}
                                    underlayColor="rgb(74, 134, 204)"
                                    onPress={actions.routes.home()}>
                    <Text  style={styles.cancelTaskText}>Отмена</Text>
                </TouchableHighlight>

            </View>
        );
    }
}

const styles = StyleSheet.create({

    layout: {
        paddingTop: 30,
        flex: 1,
        flexDirection: 'column',
        alignItems: 'center',
        backgroundColor: 'rgb(74, 134, 204)',
        color: '#ffffff'
    },

    image: {
        marginTop: 105,
        width: 100,
        height: 170,
        marginBottom: 18
    },

    mediumSpan: {
        fontSize: 18,
        textAlign: 'center',
        color: '#fff'
    },

    textInput: {
        height: 40,
        fontSize: 18,
        fontWeight: '100',
        color: '#fff'
    },

    textInputWrapper: {
        alignSelf: 'stretch',
        borderBottomColor: '#ffffff',
        borderBottomWidth: 1,
        marginBottom: 15,
        marginLeft: 23,
        marginRight: 22
    },

    createTask: {
        padding: 10,
        borderWidth: 1,
        borderColor: '#ffffff',
        borderStyle: 'solid'
    },

    createTaskText: {
        color: '#fff',
        fontSize: 18,
        fontWeight: '100'
    },

    cancelTask: {
        padding: 10
    },

    cancelTaskText: {
        color: '#fff',
        fontSize: 18,
        fontWeight: '100'
    },
});





